#services:
#  postgres:
#    image: postgres:latest
#    container_name: chat-memory-postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=ai_chat_memory_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#      - TZ=Asia/Kolkata
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d ai_chat_memory_db" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#
#volumes:
#  postgres_data:


services:
  pgvector-db:
    image: pgvector/pgvector:pg16
    container_name: rag-vector-postgres
    restart: always
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vector_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-vector-db:
    image: redis/redis-stack-server:7.4.0-v8
    container_name: rag-redis-stack
    restart: always
    ports:
      - "6379:6379"   # Default Redis data port
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
  redis_data: