spring:
  application:
    name: lecture-04-rag-vectorstore

  # 1. Postgres Connection (Required for JDBC Chat Memory)
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db?timezone=Asia/Kolkata
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # 2. Redis Connection (Required for Vector Store)
  data:
    redis:
      host: localhost
      port: 6379

  ai:
    ollama:
      base-url: http://localhost:11434
      # The Chat Model (used to generate the final text answer)
      chat:
        options:
          model: gemma4:e2b
      # The Embedding Model (used to convert documents into math vectors)
      embedding:
        options:
          model: nomic-embed-text:latest

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    # 3. Vector Store Configuration
    vectorstore:
      redis:
        # Automatically creates the RediSearch index
        initialize-schema: true
        index-name: spring-ai-index
        prefix: "embedding:"

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG